import { ArrowRight, BookOpen, CheckCircle2, Clock3, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import api, { errorMessage } from "../services/api";

export default function Dashboard() {
  const { user } = useAuth();
  const [enrollments, setEnrollments] = useState([]);
  const [error, setError] = useState("");
  useEffect(() => { api.get("/enrollments/my").then(({ data }) => setEnrollments(data.enrollments.filter((e) => e.status !== "cancelled"))).catch((e) => setError(errorMessage(e))); }, []);
  const completed = enrollments.filter((item) => item.status === "completed").length;
  return (
    <section className="dashboard-page"><div className="dashboard-welcome"><div><div className="eyebrow"><span className="eyebrow-line" /> YOUR LEARNING SPACE</div><h1>Hello, {user?.name?.split(" ")[0] || "there"}<span className="welcome-mark">✳</span></h1><p>Every little bit of learning adds up. Here’s where you are.</p></div><Link className="button button-primary" to="/courses">Find a new course <ArrowRight size={16} /></Link></div><div className="stats-row"><article><span className="stat-icon peach-icon"><BookOpen size={18} /></span><div><strong>{enrollments.length}</strong><span>Courses started</span></div></article><article><span className="stat-icon mint-icon"><CheckCircle2 size={18} /></span><div><strong>{completed}</strong><span>Courses completed</span></div></article><article><span className="stat-icon lilac-icon"><Sparkles size={18} /></span><div><strong>{enrollments.length ? Math.round(enrollments.reduce((sum, item) => sum + (item.progress?.percentage || 0), 0) / enrollments.length) : 0}%</strong><span>Average progress</span></div></article></div><div className="dashboard-section-heading"><div><div className="eyebrow">A LITTLE MORE, WHEN YOU’RE READY</div><h2>Your courses</h2></div><span>{enrollments.length} {enrollments.length === 1 ? "course" : "courses"}</span></div>{error && <div className="notice error">{error}</div>}{enrollments.length ? <div className="learning-list">{enrollments.map((item, index) => { const course = item.course; const progress = item.progress?.percentage || 0; const nextLesson = course.lessons?.find((lesson) => !item.progress?.completedLessons?.some((done) => done.toString() === lesson._id)); return <article className="learning-card" key={item._id}><div className={`learning-art ${["lavender", "peach", "mint"][index % 3]}`}>{course.imageUrl ? <img src={course.imageUrl} alt="" /> : <span>{course.title.slice(0, 1)}</span>}</div><div className="learning-info"><span className="course-category">{course.category} · {course.level}</span><h3>{course.title}</h3><span className="next-lesson"><Clock3 size={14} /> {nextLesson ? `Next: ${nextLesson.title}` : "All lessons complete"}</span><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><div className="progress-label"><span>{progress}% complete</span><span>{course.lessons?.length || 0} lessons</span></div></div><Link className="button button-outline" to={`/learn/${course._id}`}>{progress ? "Continue" : "Start learning"} <ArrowRight size={15} /></Link></article>; })}</div> : !error && <div className="dashboard-empty"><div className="empty-illustration">✳</div><div><h3>Your learning journey starts anywhere.</h3><p>Browse a few courses and choose the one that feels right for you.</p><Link className="button button-primary" to="/courses">Explore courses <ArrowRight size={16} /></Link></div></div>}</section>
  );
}
